GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/?priority=HIGH

###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/todos/?search_q=Play


###
GET http://localhost:3000/todos/2/

###
POST http://localhost:3000/register
Content-Type: application/json 

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}  


###
POST http://localhost:3000/login
Content-Type: application/json 

{
  "username": "adam_richard",
  "password": "richard_567"
}

###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}

